---
resources:
  - name: resource-app
    type: git
    source:
      uri: https://github.com/aditmeno/raindrop.git
  
  - name: cloudfoundry-ak
    type: cf
    source:
      api: ((cf_api))
      username: ((cf_username))
      password: ((cf_password))
      organization: ((cf_org))
      space: ((cf_space))
      skip_cert_check: true

jobs:
  - name: raindrop-tests
    public: true
    plan:
      - get: resource-app
        trigger: true
      - task: raindrop-tests
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang, tag: 1.12}
          
          inputs:
            - name: resource-app

          run:
            path: sh
            args: 
              - -exc
              - |
                cd resource-app
                go get -u github.com/onsi/ginkgo/ginkgo
                go get -u github.com/onsi/gomega/...
                go test ./...

  - name: raindrop-build
    public: true
    plan:
      - get: resource-app
        trigger: true
        passed: [raindrop-tests]
      - task: raindrop-build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: golang, tag: 1.12}
          
          inputs:
            - name: resource-app

          run:
            path: sh
            args: 
              - -exc
              - |
                cd resource-app
                go get -u github.com/onsi/ginkgo/ginkgo
                go get -u github.com/onsi/gomega/...
                go build ./...

      - put: cloudfoundry-ak

          

