resources:
  - name: resource-app
    type: git
    source:
      uri: https://github.com/aditmeno/raindrop.git

jobs:
  - name: job-raindrop
    public: true
    plan:
      - task: raindrop-am
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: 
              repository: golang
              tag: '1.12'
          inputs:
            - name: resource-app
              path: gopath/src/Raindrop
          run:
            path: /bin/sh
            args: [go run ./...]
            

